### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by JohnTordur** [JoysOfCode/sveltekit-auth-cookies#1]
Steps to reproduce:
- Cloned the project
- Completed the steps in the README.md

The server emits this error, when running `npm run dev`, and no page is loaded:
```
Function called outside component initialization
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:953:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:985:5)
    at root.svelte:14:1
    at $$render (/node_modules/svelte/internal/index.mjs?v=39878779:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=39878779:1778:26)
    at render_response (file:///Users/john/Code/JoysOfCode/sveltekit-auth-cookies/.svelte-kit/runtime/server/index.js:1283:27)
    at async respond_with_error (file:///Users/john/Code/JoysOfCode/sveltekit-auth-cookies/.svelte-kit/runtime/server/index.js:2663:10)
    at async respond$1 (file:///Users/john/Code/JoysOfCode/sveltekit-auth-cookies/.svelte-kit/runtime/server/index.js:2918:4)
    at async resolve (file:///Users/john/Code/JoysOfCode/sveltekit-auth-cookies/.svelte-kit/runtime/server/index.js:3303:11)
    at async Object.handle (/Users/john/Code/JoysOfCode/sveltekit-auth-cookies/src/hooks.ts:14:11)
    ```
    
    I run on Mac:
    Node version: v18.5.0
    npm version: 8.12.1

**Comment by JohnTordur** [comment]
I found the exact same issue posted to sveltejs/kit, here:
[issue on sveltejs/kit](https://github.com/sveltejs/kit/issues/5495)
Upgrading to version 1.0.0-next.371 solves it.
