### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by shadowempire123** [JoysOfCode/sveltekit-auth-cookies#6]
Hi,
following your Project Setup on https://github.com/joysofcode/sveltekit-auth-cookies
I get this error when trying to register a new user (test/test1)

![image](https://user-images.githubusercontent.com/26248866/194048905-03c06b50-8313-495e-b12d-aa9239d549e9.png)

` ➜  Local:   http://localhost:4173/
  ➜  Network: use --host to expose
Error: 
Invalid prisma.user.create() invocation:

An operation failed because it depends on one or more records that were required but not found. No 'Roles' record(s) (needed to inline the relation on 'User' record(s)) was found for a nested connect on one-to-many relation 'RolesToUser'.
    at RequestHandler.handleRequestError (D:\work\nodejs\sveltekit-auth-cookies\node_modules\@prisma\client\runtime\index.js:30851:13)
    at RequestHandler.request (D:\work\nodejs\sveltekit-auth-cookies\node_modules\@prisma\client\runtime\index.js:30834:12)
    at async PrismaClient._request (D:\work\nodejs\sveltekit-auth-cookies\node_modules\@prisma\client\runtime\index.js:31812:16)
    at async register (file:///D:/work/nodejs/sveltekit-auth-cookies/.svelte-kit/output/server/entries/pages/(auth)/register/_page.server.ts.js:22:3)
    at async handle_action_json_request (file:///D:/work/nodejs/sveltekit-auth-cookies/.svelte-kit/output/server/index.js:332:18)
    at async resolve (file:///D:/work/nodejs/sveltekit-auth-cookies/.svelte-kit/output/server/index.js:1984:22)
    at async Object.handle (file:///D:/work/nodejs/sveltekit-auth-cookies/.svelte-kit/output/server/chunks/hooks.server.js:5:12)
    at async respond (file:///D:/work/nodejs/sveltekit-auth-cookies/.svelte-kit/output/server/index.js:2022:22)
    at async file:///D:/work/nodejs/sveltekit-auth-cookies/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:145:5
Error:
Invalid `prisma.user.create()` invocation:`

**Comment by tiwhi** [comment]
You need to manually create the 'Roles' records in your database first. The error is saying there are no records in the Roles table to link with your user. If you follow the database setup section in his blog post he explains it. You can add the roles manually using prisma studio by running npx prisma studio.
https://joyofcode.xyz/sveltekit-authentication-using-cookies#setting-up-the-database

**Comment by mcurcija** [comment]
The instructions regarding DB setup are bit unclear.
Start prisma studio: 
`pnpx prisma studio`

and open http://localhost:5555 in your browser afterwards
Add role with content  "USER" (it has to be [upper-cased](https://github.com/joysofcode/sveltekit-auth-cookies/blob/00b665bfde138694686d499a98fe32bcfbf69b76/src/routes/(auth)/register/%2Bpage.server.ts#L9)) 

The registration action should be successful after that.

**Comment by matiadev** [comment]
Thanks, I updated the instructions https://github.com/joysofcode/sveltekit-auth-cookies/commit/0c34beb77119b7949c3282c4721beac10c66c412! 😄

**Comment by shadowempire123** [comment]
thx!
